version: "3"

services:
  mongo:
    image: "mongo"
    container_name: "mongodb"
    volumes:
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/db
    ports:
      - "27017:27017"
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=user
      # - MONGO_INITDB_ROOT_PASSWORD=password
      # - MONGO_INITDB_DATABASE=mytestdatabase
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"